## General

# Dependencies
markdown:         kramdown
highlighter:	  pygments
pygments_options: ['lineanchors']

kramdown:
    fenced_code_blocks: true

# Permalinks
permalink:        pretty

safe: false

# Setup
title:            Donghui Nong
tagline:          'Nebulous thoughts'
description:      'Maybe somebody, somewhere will find this useful.'
url:              https://nongdonghui.github.io
enforce_url:      nongdonghui.github.io
baseurl:          /

author:
  name:           'Donghui Nong'
  #url:            https://twitter.com/nongdonghui

paginate:         5

gems:
    - jekyll-redirect-from
    - jekyll-paginate
    - jekyll-sitemap
    - pygments.rb
    - yui/compressor
    - execjs

include:
    - .nojekyll

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md

## Plugins vars

# Config for sitemap_generator.rb
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Config for css_compressor.rb plugin
compressor:
    path_to_css: "./_assets/css/"
    path_to_output: "./public/css/"
    css_filenames:
        - "poole.css"
        - "syntax.css"
        - "lanyon.css"
        - "bootstrap_button.css"
        - "font-awesome.min.css"
        - "katex.min.css"
        - "custom.css"
    output_fname: "stylesheets.css"

# Config for katex_block.rb plugin
katex:
    path_to_js: "./public/js/katex.min.js"

## Custom vars
#
version:          1.1.0

github:
  user:           https://github.com/nongdonghui
  repo:           https://github.com/nongdonghui/nongdonghui.github.io
